### ISSUE TITLE
Feature Request- Hot Key or multi key command to prettify

### ISSUE THREAD

**Issue by aaron-robles** [federomero/pretty-json#69] opened 2017-07-02 18:22 UTC
Big fan of this and the XML formatter. One thing I've noticed that is really helpful is that I can do CMD+SHIFT+X to format XML with the other package I used. If there could be a user defined command to do this with pretty-json that'd be fantastic!

**Comment by lexicalunit** [comment] 2017-07-05 19:48
Closing as duplicate of #63. Please see [my comment there](https://github.com/federomero/pretty-json/issues/63#issuecomment-268646525), @aaron-robles, for details on how to add a keyboard shortcut for any command you use frequently. It may come in handy to know for more than just this package! 🎉

**Closed by lexicalunit** 2017-07-05 19:48 UTC
